-- TODO original vim config
-- let g:grepper.rg.grepprg .= ' --smart-case'
-- let g:grepper.operator.prompt = 1
-- let g:grepper.operator.tool = 'rg'
-- nnoremap <leader>a :Grepper -tool ag<cr>
-- nnoremap <leader>r :Grepper -tool rg<cr>
-- nmap gs  <plug>(GrepperOperator)
-- xmap gs  <plug>(GrepperOperator)
-- let g:grepper.dir = 'repo,filecwd'

-- TODO examine grepper settings from:
-- https://github.com/kevinhwang91/nvim-bqf#integrate-with-other-plugins
