# reminder: ksh uses '.' , not 'source'

#https://stackoverflow.com/questions/1171663/how-to-custom-display-prompt-in-kornshell-to-show-hostname-and-current-directory
# https://man.openbsd.org/ksh#PS1

PS1="[\u@\h:\W]\$ "

# http://superuser.com/questions/266534/using-readline-keyboard-shortcuts-in-osx-korn-shell#266542
#test -t 0 && set -o emacs
#export PATH=$HOME/bin:$HOME/workspace/inferno-os/OpenBSD/386/bin:$HOME/.gem/ruby/2.3/bin:$PATH

# load completions
. "$HOME/.ksh_completions"

# activate history
HISTFILE="$HOME/.ksh_history"
# Note that openbsd ksh doesn't seem to have a pattern-ignore(like bash), and doesn't like multiples in this setting
HISTCONTROL=ignoredups

# Additions
export FZF_DEFAULT_COMMAND='rg --files'
# zoxide/z

# Rust setup
export RUST_BIN=$HOME/.cargo/bin
export PATH=$PATH:/$RUST_BIN

# z / zoxide setup
eval "$(zoxide init bash)"

# Ruby
# This ensures that gem executables(like bundler) get picked up
export PATH=$PATH:$GEM_HOME/bin
