#xset +fp /usr/local/share/fonts/ghostscript/
#xset +fp /usr/local/share/fonts/Droid/
#xset +fp /usr/local/share/fonts/terminus/
#xset +fp /usr/local/share/fonts/Inconsolata/
xset +fp /usr/local/share/fonts/ghostscript/
xset +fp /usr/local/share/fonts/noto/
xset +fp /usr/local/share/fonts/terminus/
xset +fp /usr/local/share/fonts/inconsolata/
xset +fp /usr/local/share/fonts/fira/
xset +fp /usr/local/share/fonts/roboto
xset fp rehash

xrdb -merge $HOME/.Xdefaults

# Must use external config to get multiple options: in this case, both nocaps and altwin
setxkbmap -config /home/mecha/.xkb_config

# Shifts when pressed alone type parentheses. When used with other keys they're normal shifts.
xcape -e 'Shift_L=Shift_L|parenleft;Shift_R=Shift_L|parenright'

eval $(ssh-agent)

xscreensaver -no-splash &

dstat iwm0 &

exec dwm
