# ksh uses '.' , not 'source'
#. "$HOME/.homesick/repos/homeshick/bin/homeshick.csh"

# https://stackoverflow.com/questions/1171663/how-to-custom-display-prompt-in-kornshell-to-show-hostname-and-current-directory
PS1="${HOSTNAME}:\${PWD##*/} \$ "

#PS1='${red}[${end}$(id -un)@\h${yellow}: ${end}$(date "+%a, %h-%d %l:%M%p")${red}]${end}\n${green}${PWD}${end}${yellow}/${end}'

# http://superuser.com/questions/266534/using-readline-keyboard-shortcuts-in-osx-korn-shell#266542
test -t 0 && set -o emacs
export PATH=$HOME/bin:$HOME/workspace/inferno-os/OpenBSD/386/bin:$HOME/.gem/ruby/2.3/bin:$PATH
